### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by wudicsy** [mohuaiyuan2015/SetOowerOffOnTest#2]
华为的手机，系统安卓10，点击设置按钮有空指针异常
<img width="1192" alt="屏幕快照 2020-09-01 下午2 50 51" src="https://user-images.githubusercontent.com/13570475/91811773-9e006e80-ec62-11ea-98ec-cf73de79907f.png">
<img width="1109" alt="屏幕快照 2020-09-01 下午2 51 08" src="https://user-images.githubusercontent.com/13570475/91811813-ad7fb780-ec62-11ea-90b1-4b72784fad2b.png">

**Comment by mohuaiyuan2015** [comment]
> 华为的手机，系统安卓10，点击设置按钮有空指针异常
> <img alt="屏幕快照 2020-09-01 下午2 50 51" width="1192" src="https://user-images.githubusercontent.com/13570475/91811773-9e006e80-ec62-11ea-98ec-cf73de79907f.png">
> <img alt="屏幕快照 2020-09-01 下午2 51 08" width="1109" src="https://user-images.githubusercontent.com/13570475/91811813-ad7fb780-ec62-11ea-90b1-4b72784fad2b.png">

不好意思，这个是 针对 一款特定的Android设备的App 。不适用市场上的Android系统的设备（包括手机等）啦。

**Comment by wudicsy** [comment]
好的好的，没关系~
